version: '3'
services:
  docker-mysql:
    image: mysql:latest
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/BO/services/docker-mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
